-- 1. Criar a tabela 'prompts' (caso não exista)
CREATE TABLE IF NOT EXISTS public.prompts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  prompt_text TEXT NOT NULL,
  username TEXT NOT NULL,
  avatar TEXT NOT NULL,
  post_title TEXT NOT NULL,
  post_subtitle TEXT NOT NULL,
  gradient TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar Segurança em Nível de Linha (RLS)
ALTER TABLE public.prompts ENABLE ROW LEVEL SECURITY;

-- 3. Criar política para permitir que usuários autenticados possam ler os dados (cria condicionalmente caso n tenha)
DO $$
BEGIN
  IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE tablename = 'prompts' AND policyname = 'Permitir leitura para usuários autenticados'
  ) THEN
      CREATE POLICY "Permitir leitura para usuários autenticados" ON public.prompts
        FOR SELECT TO authenticated USING (true);
  END IF;
END $$;

-- 4. Limpar os dados antigos para evitar duplicação (caso rode este script várias vezes)
TRUNCATE TABLE public.prompts RESTART IDENTITY;

-- 5. Inserir os 12 prompts completos (com o seu avatar "AS" e perfil "@adriansoares.mkt" configurados para todos)
INSERT INTO public.prompts (title, description, category, prompt_text, username, avatar, post_title, post_subtitle, gradient) VALUES
(
  'Relatório de Análise Windsor.ai + Claude',
  'O Prompt mestre para analisar Windsor.ai e gerar diagnósticos profundos de crescimento e pontos de retenção.',
  'Diagnóstico',
  'Você é um estrategista sênior de crescimento no Instagram com especialidade em análise de dados de criadores de conteúdo.

Acesse os dados do meu perfil via Windsor.ai e execute um diagnóstico completo seguindo esta estrutura:

**VISÃO GERAL DO PERÍODO**
- Período analisado
- Total de publicações
- Alcance acumulado e impressões totais
- Variação em relação ao período anterior (%)

**DIAGNÓSTICO DE RETENÇÃO**
- Taxa de retenção média dos vídeos
- Os 3 vídeos com maior retenção: o que eles têm em comum?
- Os 3 vídeos com menor retenção: onde as pessoas saem?
- Padrão identificado nos primeiros 3 segundos dos vídeos que performam

**PONTOS DE CRESCIMENTO**
- Quais tipos de conteúdo geraram mais seguidores novos?
- Qual horário e dia da semana teve melhor desempenho?
- Qual formato (Reels, carrossel, estático) trouxe mais alcance orgânico?

**DIAGNÓSTICO HONESTO**
- O que está travando o crescimento agora?
- Qual o maior erro que estou cometendo com base nos dados?

**PLANO DE AÇÃO — PRÓXIMOS 30 DIAS**
- 3 mudanças imediatas a implementar
- Tipo de conteúdo para priorizar
- Meta realista de crescimento baseada nos dados históricos

Seja direto, use os dados reais e não suavize os problemas encontrados. Quero um diagnóstico honesto, não elogios.',
  'adriansoares.mkt',
  'AS',
  'O PROMPT MESTRE DE CRESCIMENTO',
  'Windsor.ai + Claude 3.5 Sonnet',
  'from-indigo-950 via-slate-900 to-black'
),
(
  'Roteiro de Reels Viral de Alto Engajamento',
  'A estrutura de roteiro com ganchos estratégicos para garantir retenção nos primeiros 3 segundos.',
  'Roteiros',
  'Você é um roteirista especializado em Reels virais com foco em retenção máxima nos primeiros 3 segundos.

Crie um roteiro completo para um Reel de [DURAÇÃO: ex. 30 / 45 / 60 segundos] sobre o tema: [TEMA DO VÍDEO]

**ESTRUTURA DO ROTEIRO:**

SEGUNDO 0–3 (GANCHO VISUAL + VERBAL)
- O que aparece na tela
- Exatamente o que eu falo (palavra por palavra)
- Por que esse gancho funciona

SEGUNDO 3–15 (DESENVOLVIMENTO)
- O que mostro ou explico
- Falas principais
- Transições ou cortes sugeridos

SEGUNDO 15–25 (VIRADA OU REVELAÇÃO)
- O momento de surpresa ou valor máximo
- Falas exatas

SEGUNDO 25–[FIM] (CTA)
- Call to action irresistível
- Fala exata para encerrar

**ELEMENTOS DE PRODUÇÃO:**
- Sugestão de texto na tela (captions)
- Mood da música (ritmo, energia, estilo)
- Ângulo de câmera sugerido

**LEGENDA COMPLETA:**
- Primeira linha (aparece antes do "ver mais") — deve gerar clique
- Corpo da legenda
- CTA final
- 5 hashtags estratégicas para esse conteúdo

Adapte o roteiro para que funcione mesmo sem áudio, pois muitos assistem no mudo.',
  'adriansoares.mkt',
  'AS',
  'ROTEIRO REELS VIRAL',
  'Retenção nos 3 Primeiros Segundos',
  'from-fuchsia-950 via-neutral-900 to-black'
),
(
  'Gerador de Linha Editorial Infinita',
  'Construa 3 pilares de conteúdo magnéticos e nunca mais passe um único dia sem ideias poderosas para postar.',
  'Feed',
  'Você é uma editora de conteúdo estratégico especializada em criadores de conteúdo do Instagram.

Meu nicho é: [NICHO]
Meu público-alvo é: [DESCREVA: ex. empreendedores iniciantes, mães que trabalham em casa, etc.]
Minha dor principal que resolvo: [DOR]

**TAREFA:**
Construa meus 3 Pilares de Conteúdo Magnético — os temas centrais que vão guiar TUDO que eu posto.

Para cada pilar entregue:

**PILAR [número]: [NOME DO PILAR]**
- Por que esse pilar atrai e retém seguidores no meu nicho
- 5 ideias de Reels para esse pilar (com gancho já escrito)
- 5 ideias de carrossel (com título do primeiro slide)
- 3 ideias de conteúdo de bastidor ou prova social
- Frequência ideal de postagem desse pilar por semana

**CALENDÁRIO DE ROTAÇÃO:**
- Como intercalar os 3 pilares ao longo da semana
- Qual pilar postar em qual dia para maximizar engajamento

**REGRA DE OURO DO MEU CONTEÚDO:**
- Uma frase que resume o que meu perfil entrega e que devo ter em mente antes de postar qualquer coisa

No final, me dê o nome dos 3 pilares em formato de slogan — curto, memorável, que eu possa usar internamente como guia.',
  'adriansoares.mkt',
  'AS',
  'EDITORA INFINITA',
  '3 Pilares de Conteúdo Magnéticos',
  'from-cyan-950 via-neutral-900 to-black'
),
(
  'Sequência de Stories Dominantes de Vendas',
  'Roteiro de 5 stories estruturados com prova social para disparar caixas de entrada de direct interessados.',
  'Stories',
  'Você é um especialista em storytelling para Instagram Stories com foco em conversão para direct e vendas.

Meu produto/serviço: [DESCREVA O PRODUTO]
Preço: [PREÇO]
Principal resultado que entrego: [RESULTADO EM 1 FRASE]
Objeção mais comum do meu público: [OBJEÇÃO]

Crie uma sequência de 5 Stories estruturados para gerar caixas de direct cheias de interessados.

**STORY 1 — GANCHO (desperta curiosidade)**
- Visual sugerido
- Texto exato
- Elemento interativo (enquete, pergunta, caixinha)

**STORY 2 — IDENTIFICAÇÃO (faz o seguidor se ver)**
- Visual sugerido
- Texto exato
- Como criar conexão emocional

**STORY 3 — PROVA SOCIAL (quebra ceticismo)**
- Tipo de prova a usar (print, depoimento, resultado)
- Como apresentar sem parecer forçado
- Texto exato

**STORY 4 — VIRADA (apresenta a solução)**
- Como introduzir o produto naturalmente
- Texto exato
- Transição para a oferta

**STORY 5 — OFERTA + CTA (dispara o direct)**
- Como apresentar o preço sem gerar resistência
- CTA exato (palavra por palavra)
- Elemento de urgência ou escassez

**DICA DE POSTAGEM:**
- Melhor horário para essa sequência
- Como reaproveitar esses stories como destaque

Escreva os textos como se eu fosse copiar e colar direto no Stories — linguagem natural, sem parecer roteirizado.',
  'adriansoares.mkt',
  'AS',
  'MÁQUINA DE STORIES',
  'Script de 5 Passos e Oferta Direta',
  'from-amber-950 via-neutral-900 to-black'
),
(
  'Script para Automação ManyChat Inteligente',
  'Combine prompts que entregam bônus digitais convertendo leads frios em compradores em segundos.',
  'Vendas',
  'Você é um especialista em automações de Manychat e funis de conversão para Instagram.

Meu produto: [PRODUTO]
Palavra-gatilho que o seguidor vai comentar ou enviar: [PALAVRA-GATILHO: ex. "PROMPT", "QUERO", "INFO"]
Preço do produto: [PREÇO]
Link de compra ou checkout: [LINK]

Crie uma sequência completa de mensagens automáticas no Manychat para transformar leads frios em compradores. A sequência deve acontecer no direct.

**MENSAGEM 1 — RESPOSTA IMEDIATA (enviada em até 1 minuto)**
Texto exato da primeira mensagem automática. Deve:
- Reconhecer o interesse
- Entregar o que foi prometido (link, conteúdo, acesso)
- Criar curiosidade para a próxima mensagem

**MENSAGEM 2 — AQUECIMENTO (enviada 30 min depois)**
Texto exato. Deve:
- Verificar se a pessoa acessou
- Apresentar o maior resultado do produto
- Fazer uma pergunta que gere resposta

**MENSAGEM 3 — QUEBRA DE OBJEÇÃO (enviada 2h depois)**
Texto exato. Deve:
- Antecipar a principal dúvida ou medo
- Respondê-la de forma direta
- Incluir prova social (resultado de aluno ou cliente)

**MENSAGEM 4 — OFERTA DIRETA (enviada 24h depois)**
Texto exato. Deve:
- Fazer a oferta sem rodeios
- Criar urgência real (não falsa)
- Ter CTA claro com link de compra

**REGRAS DE ESCRITA:**
- Linguagem de conversa, não de vendedor
- Mensagens curtas (máximo 5 linhas cada)
- Sem emojis em excesso
- Nunca parecer robótico',
  'adriansoares.mkt',
  'AS',
  'MANYCHAT INTELIGENTE',
  'Leads Frios em Clientes Ativos',
  'from-violet-950 via-neutral-900 to-black'
),
(
  'Banco de Títulos Magnéticos (Hooks de Capa)',
  'Vinte Modelos de copys testadas para capas e reels prontos para preencher e viralizar no feed.',
  'Roteiros',
  'Você é um especialista em copywriting para capas de Reels e carrosséis no Instagram.

Meu nicho: [NICHO]
Meu público-alvo: [PÚBLICO]
Os 3 principais resultados que meu conteúdo entrega: [RESULTADO 1], [RESULTADO 2], [RESULTADO 3]

Crie 20 hooks prontos para usar como texto de capa, organizados por formato:

**FORMATO 1 — PERGUNTA PROVOCATIVA (4 hooks)**
Perguntas que causam identificação imediata ou medo de estar errando algo.

**FORMATO 2 — AFIRMAÇÃO POLÊMICA (4 hooks)**
Frases que contradizem o senso comum do nicho e geram parada no scroll.

**FORMATO 3 — NÚMERO + PROMESSA (4 hooks)**
Ex: "3 erros que..." / "7 dias para..." / "1 hábito que..."

**FORMATO 4 — REVELAÇÃO CHOCANTE (4 hooks)**
Começa com "Ninguém te contou que...", "O segredo que...", "Isso que você faz está..."

**FORMATO 5 — PROVA DE RESULTADO (4 hooks)**
Hooks baseados em transformação real: antes/depois, tempo, número específico.

**REGRAS DOS HOOKS:**
- Máximo de 8 palavras cada
- Sem ponto final (capa não tem ponto final)
- Deve funcionar mesmo sem ver o restante do vídeo
- Deve causar uma dessas emoções: curiosidade, medo de perder, identificação ou inveja positiva

No final, me diga qual dos 20 tem maior potencial viral para o meu nicho e por quê.',
  'adriansoares.mkt',
  'AS',
  '20 HOOKS DE CAPA',
  'Títulos e Copys Prontas para Viralizar',
  'from-rose-950 via-neutral-900 to-black'
),
(
  'Cronograma de Postagens 30 Dias do Zero',
  'Planeje e escreva um mês de conteúdos estratégicos de valor e engajamento em poucos minutos.',
  'Feed',
  'Você é um estrategista de conteúdo para Instagram especializado em crescimento acelerado de perfis do zero.

Meu nicho: [NICHO]
Minha situação atual: [ex. perfil novo, perfil parado há meses, perfil com X seguidores sem engajamento]
Quanto tempo tenho por dia para criar conteúdo: [ex. 1 hora / 2 horas]
Meu objetivo em 30 dias: [ex. chegar em 1.000 seguidores, gerar primeiras vendas, reativar perfil]

Crie um plano de conteúdo de 30 dias, dia a dia, com tudo que preciso fazer.

**SEMANA 1 — FUNDAÇÃO (dias 1 a 7)**
Para cada dia:
- Tipo de conteúdo (Reel, carrossel, estático, story)
- Tema específico do post
- Gancho pronto para usar
- Objetivo daquele conteúdo (alcance, engajamento, seguidores, vendas)

**SEMANA 2 — ACELERAÇÃO (dias 8 a 14)**
[mesma estrutura]

**SEMANA 3 — AUTORIDADE (dias 15 a 21)**
[mesma estrutura]

**SEMANA 4 — CONVERSÃO (dias 22 a 30)**
[mesma estrutura]

**REGRAS DO PLANO:**
- Variar entre os 3 pilares de conteúdo ao longo das semanas
- Incluir pelo menos 1 conteúdo de prova social por semana
- Incluir pelo menos 1 oferta ou CTA de venda na semana 3 e 4
- Considerar que sou uma pessoa só, sem equipe

**CHECKLIST DIÁRIO:**
Lista de 5 ações rápidas que devo fazer todo dia além de postar (comentar em perfis do nicho, responder stories, etc.)

Seja específico. Não quero temas genéricos — quero títulos e ganchos prontos para usar.',
  'adriansoares.mkt',
  'AS',
  '30 DIAS DO ZERO',
  'Cronograma de Conteúdo Estratégico',
  'from-emerald-950 via-neutral-900 to-black'
),
(
  'Funil de Direct Lucrativo e Conversor',
  'Prompts para treinar o Claude a qualificar e interagir com leads quentes sem parecer robótico.',
  'Vendas',
  'Você é um consultor de vendas especializado em conversas de direct no Instagram. Sua missão é me ajudar a criar scripts de conversa para qualificar leads frios e conduzi-los à compra de forma natural.

Meu produto: [PRODUTO]
Preço: [PREÇO]
Resultado principal: [RESULTADO]
Perfil ideal de cliente: [DESCREVA: ex. criador de conteúdo com mais de 1.000 seguidores que quer monetizar]

Crie um script completo de conversa de direct para 3 cenários diferentes:

**CENÁRIO 1 — Lead veio pelo Manychat (pediu info no post)**
Script de abertura + qualificação + apresentação da oferta
(5 a 7 mensagens, tom consultivo)

**CENÁRIO 2 — Lead interagiu no story mas não pediu info**
Como abordar sem parecer invasivo
Script de abertura + quebra-gelo + transição para oferta
(4 a 6 mensagens)

**CENÁRIO 3 — Lead sumiu após receber o preço**
Script de follow-up 24h depois
Como reabrir a conversa sem parecer desesperado
(2 a 3 mensagens)

**PARA CADA SCRIPT:**
- Mensagens exatas, prontas para copiar
- Explicação do porquê de cada mensagem funcionar
- O que fazer se a pessoa não responder

**REGRAS DE OURO DA CONVERSA:**
- Nunca mandar áudio não solicitado
- Sempre fazer uma pergunta por vez
- Nunca mandar o link antes de qualificar
- Se a pessoa perguntar o preço antes de estar qualificada, o que responder',
  'adriansoares.mkt',
  'AS',
  'FUNIL DE DIRECT',
  'Claude Qualificando Seus Leads Frios',
  'from-blue-950 via-slate-900 to-black'
),
(
  'Analisador Visual de Feedback & Comentários',
  'Gere respostas inteligentes baseadas no tom de voz ideal do seu perfil automaticamente.',
  'Vendas',
  'Você é um especialista em brand voice e comunicação para criadores de conteúdo no Instagram.

Vou te passar exemplos do meu conteúdo para que você identifique e construa meu tom de voz oficial.

**MEUS EXEMPLOS DE CONTEÚDO:**
[Cole aqui: 3 a 5 legendas de posts seus / transcrição de um Reel / prints de stories / como você normalmente escreve]

Com base nesses exemplos, entregue:

**ANÁLISE DO MEU TOM DE VOZ ATUAL**
- Como eu me comunico naturalmente
- Palavras e expressões que uso com frequência
- Ritmo das frases (curtas, longas, mistas)
- Emoções que transmito mais
- O que está funcionando e o que está inconsistente

**MEU TOM DE VOZ OFICIAL**
- 5 adjetivos que descrevem como meu perfil deve soar
- O que eu NUNCA devo escrever (palavras e estilos que fogem da minha voz)
- O que eu SEMPRE devo incluir (elementos que me identificam)

**GUIA PRÁTICO**
- Como escrever uma legenda no meu tom de voz (passo a passo)
- Como adaptar minha voz para Reels, carrosséis e stories (são diferentes)
- 3 exemplos de legendas reescritas no meu tom oficial

**FRASES-ÂNCORA**
5 frases que capturam minha essência e que posso usar como referência sempre que criar conteúdo novo.

Agora, com base em tudo que identificou, reescreva este texto no meu tom de voz:
[COLE AQUI UM TEXTO QUE VOCÊ QUER ADAPTAR]',
  'adriansoares.mkt',
  'AS',
  'ANALISADOR DE COMUNIDADE',
  'Tom de Voz Perfeito e Automático',
  'from-sky-950 via-neutral-900 to-black'
),
(
  'Roteiro de Carrossel de Alta Retenção',
  'A sequência de dobras de slides visualmente envolventes projetada para audiências exigentes.',
  'Feed',
  'Você é um especialista em carrosséis de alta retenção para Instagram, com foco em fazer o seguidor deslizar até o último slide e clicar no CTA.

Tema do carrossel: [TEMA]
Objetivo: [ex. gerar salvamentos, conseguir seguidores, vender produto X]
Público: [PÚBLICO-ALVO]

Crie a estrutura completa de um carrossel de [NÚMERO DE SLIDES: recomendado entre 7 e 10] slides.

**SLIDE 1 — CAPA (o mais importante)**
- Título exato (máximo 7 palavras)
- Subtítulo ou complemento (opcional)
- Por que essa capa vai parar o scroll

**SLIDES 2 A [N-1] — DOBRAS DE CONTEÚDO**
Para cada slide:
- Número do slide
- Título do slide
- Texto de suporte (2 a 3 linhas máximo)
- Elemento visual sugerido (ícone, seta, destaque)
- Gancho de transição para o próximo slide (frase que incentiva deslizar)

**SLIDE FINAL — CTA**
- Título do CTA
- Ação exata que quero que o seguidor faça
- Texto completo do slide
- Por que esse CTA funciona para esse conteúdo

**LEGENDA DO POST**
- Primeira linha (aparece antes do "ver mais") — deve gerar curiosidade
- Corpo (3 a 5 linhas completando o tema)
- CTA alinhado com o último slide
- 5 hashtags estratégicas

**DICA DE DESIGN:**
- Paleta de cores sugerida para esse tema
- Fonte de destaque vs fonte de corpo
- O que nunca colocar em carrossel (erros comuns)',
  'adriansoares.mkt',
  'AS',
  'CARROSSEL RETENÇÃO',
  'Sequência Ideal de Dobras e CTA',
  'from-amber-950 via-neutral-900 to-black'
),
(
  'Otimizador de Bio de Instagram Milionária',
  'Descubra e escreva uma oferta de promessa direta irresistível que força cliques no seu link da Bio.',
  'Diagnóstico',
  'Você é um especialista em copywriting e posicionamento para perfis do Instagram.

Me ajude a criar uma bio que transforma visitantes em seguidores e seguidores em clientes.

**MINHAS INFORMAÇÕES:**
- Meu nicho: [NICHO]
- Quem é meu cliente ideal: [DESCREVA]
- O maior resultado que entrego: [RESULTADO ESPECÍFICO]
- Meu diferencial em relação a outros do meu nicho: [DIFERENCIAL]
- Tenho produto para vender? [SIM/NÃO — qual?]
- Link da bio: [onde quero que as pessoas cliquem]

**ENTREGUE:**

**3 VERSÕES DE BIO COMPLETA**
Cada versão deve ter:
- Linha 1: Quem você ajuda + resultado (máximo 60 caracteres)
- Linha 2: Como você faz isso / seu diferencial
- Linha 3: Prova social ou credencial
- Linha 4: CTA com link ou instrução de ação
- Emoji strategy: quais emojis usar e onde (ou se não usar)

**ANÁLISE DE CADA VERSÃO**
- Para qual objetivo ela é melhor (seguidores, vendas, autoridade)
- O que a torna forte
- O que pode ser melhorado

**NOME DE PERFIL E @**
- Sugestão de nome de perfil (campo de nome, não @) otimizado para busca
- Palavras-chave para incluir

**HEADLINE PARA LINKS**
Se uso Linktree ou link na bio, qual frase usar como chamada antes do link.

Depois de apresentar as 3 versões, me pergunte qual delas mais se aproxima do que quero e refine até ficar perfeita.',
  'adriansoares.mkt',
  'AS',
  'BIO MILIONÁRIA',
  'Sua Promessa Direta Irresistível',
  'from-orange-950 via-neutral-900 to-black'
),
(
  'Abordagem Comercial de Parcerias e Altas Colabs',
  'Estrutura rápida para abordar marcas e perfis maiores garantindo abertura e bons acordos.',
  'Vendas',
  'Você é um especialista em parcerias estratégicas e co-marketing para criadores de conteúdo no Instagram.

**MINHA SITUAÇÃO:**
- Meu perfil/nicho: [NICHO]
- Tamanho atual do perfil: [SEGUIDORES]
- O que tenho para oferecer em uma parceria: [ex. audiência engajada, conteúdo de qualidade, lista de emails, produto digital]
- Tipo de parceria que busco: [ex. collab de Reel, permuta, afiliado, co-criação de produto]
- Perfil que quero abordar: [DESCREVA: tamanho, nicho, tipo de criador]

**ENTREGUE:**

**ESTRATÉGIA DE ABORDAGEM**
- Como me posicionar antes de enviar a primeira mensagem (o que fazer no perfil deles nos dias anteriores)
- Melhor canal para abordar (direct, email, comentário)
- Melhor momento para enviar

**SCRIPT DE ABORDAGEM INICIAL**
Mensagem exata para o primeiro contato. Deve:
- Mostrar que conheço o trabalho deles (personalizado, não genérico)
- Apresentar a proposta de valor de forma clara
- Não parecer pedindo favor — parecer proposta de negócio
- Máximo de 5 linhas

**SCRIPT DE FOLLOW-UP**
Se não responderem em 3 dias: mensagem exata de retomada.

**PROPOSTA FORMAL (se pedirem mais detalhes)**
Estrutura de mensagem mais completa com:
- O que cada parte ganha
- Como funcionaria a collab na prática
- Próximo passo concreto

**COMO ESCALAR**
- Como abordar 10 perfis por semana sem parecer spam
- Como organizar e acompanhar as abordagens
- O que fazer com os "não" ou os que ignoram

**TEMPLATE DE RASTREAMENTO**
Estrutura simples para acompanhar todas as abordagens ativas.',
  'adriansoares.mkt',
  'AS',
  'ABORDAGEM EM ESCALA',
  'Feche Grandes Colaborações de Sucesso',
  'from-teal-950 via-neutral-900 to-black'
);
