export const PROMPT_TEXT = `Acesse o Windsor.ai e conecte-se aos dados do meu perfil do Instagram. Com base nos dados disponíveis, gere um relatório estratégico completo seguindo esta estrutura: VISÃO GERAL DO PERÍODO Período analisado, total de publicações, alcance acumulado, impressões totais e variação em relação ao período anterior. MÉTRICAS DE CRESCIMENTO Evolução de seguidores, taxa de crescimento, perfil demográfico do público (se disponível) e tendência de curto prazo. PERFORMANCE DE ENGAJAMENTO Taxa de engajamento média, evolução por período, comparativo entre formatos (Reels, carrosséis, imagens estáticas, stories) e benchmarks se disponíveis. TOP CONTEÚDOS Liste os 5 posts com maior alcance e os 5 com maior engajamento. Para cada um: tipo de formato, data, métrica principal e hipótese do que gerou o desempenho. CONTEÚDOS DE BAIXO DESEMPENHO Identifique padrões nos conteúdos que tiveram desempenho abaixo da média. O que eles têm em comum? ANÁLISE DE FORMATOS E HORÁRIOS Qual formato performa melhor? Existe padrão de horário ou dia da semana com maior alcance ou engajamento? DIAGNÓSTICO GERAL O que está funcionando, o que está travando o crescimento e qual é o maior gap entre potencial e resultado atual. RECOMENDAÇÕES PRIORITÁRIAS 3 a 5 ações concretas e ordenadas por impacto potencial, com justificativa baseada nos dados. ROTEIROS BASEADOS NOS TOP VÍDEOS Com base nos 3 vídeos de maior engajamento identificados na seção 4, escreva um roteiro completo para cada um seguindo o mesmo padrão de estrutura, gancho, desenvolvimento e CTA que gerou resultado. Cada roteiro deve ser original, mas replicar a lógica e o formato do vídeo de referência — não o conteúdo. Indique no início de cada roteiro qual vídeo serviu de base e por que aquele padrão foi escolhido. Seja objetivo, baseie cada afirmação nos dados do Windsor. Onde não houver dados suficientes, indique a lacuna em vez de especular.`;

export const PROMPTS_DATA = [
  {
    id: 1,
    title: "Relatório de Análise Windsor.ai + Claude",
    desc: "O Prompt mestre para analisar Windsor.ai e gerar diagnósticos profundos de crescimento e pontos de retenção.",
    category: "Diagnóstico",
    text: PROMPT_TEXT,
    username: "adriansoares.mkt",
    avatar: "AS",
    postTitle: "O PROMPT MESTRE DE CRESCIMENTO",
    postSubtitle: "Windsor.ai + Claude 3.5 Sonnet",
    gradient: "from-indigo-950 via-slate-900 to-black",
  },
  {
    id: 2,
    title: "Roteiro de Reels Viral de Alto Engajamento",
    desc: "A estrutura de roteiro com ganchos estratégicos para garantir retenção nos primeiros 3 segundos.",
    category: "Roteiros",
    text: "Mapeie os 3 maiores desejos e as 3 maiores dores do meu público. Em seguida, crie um roteiro de Reels usando o framework AIDA (Atenção, Interesse, Desejo e Ação). O gancho (primeiros 3 segundos) deve focar em uma dor urgente, seguido de uma transição dinâmica, explicação visual rápida e um CTA forte para salvar o vídeo.",
    username: "graoficial",
    avatar: "GR",
    postTitle: "ROTEIRO REELS VIRAL",
    postSubtitle: "Retenção nos 3 Primeiros Segundos",
    gradient: "from-fuchsia-950 via-neutral-900 to-black",
  },
  {
    id: 3,
    title: "Gerador de Linha Editorial Infinita",
    desc: "Construa 3 pilares de conteúdo magnéticos e nunca mais passe um único dia sem ideias poderosas para postar.",
    category: "Feed",
    text: "Atue como um estrategista de conteúdo sênior. Defina 3 pilares editoriais principais para o meu nicho e gere 10 ideias de conteúdo para cada pilar, equilibrando formatos (Reels, Carrossel, Foto Única) e focando em engajamento, autoridade e conversão. Formate em uma tabela.",
    username: "larisg.digital",
    avatar: "LG",
    postTitle: "EDITORA INFINITA",
    postSubtitle: "3 Pilares de Conteúdo Magnéticos",
    gradient: "from-cyan-950 via-neutral-900 to-black",
  },
  {
    id: 4,
    title: "Sequência de Stories Dominantes de Vendas",
    desc: "Roteiro de 5 stories estruturados com prova social para disparar caixas de entrada de direct interessados.",
    category: "Stories",
    text: "Crie um roteiro detalhado para uma sequência de 5 Stories voltados para venda. 1º Story: Enquete polarizadora sobre a dor principal. 2º: Conscientização do problema. 3º: Prova social (print de resultado). 4º: Apresentação da solução (meu produto/serviço). 5º: CTA claro e urgente para responder 'EU QUERO' no direct.",
    username: "thiago.mkt",
    avatar: "TM",
    postTitle: "MÁQUINA DE STORIES",
    postSubtitle: "Script de 5 Passos e Oferta Direta",
    gradient: "from-amber-950 via-neutral-900 to-black",
  },
  {
    id: 5,
    title: "Script para Automação ManyChat Inteligente",
    desc: "Combine prompts que entregam bônus digitais convertendo leads frios em compradores em segundos.",
    category: "Vendas",
    text: "Quero criar um fluxo no ManyChat. O gatilho é um comentário no Reels com a palavra secreta. Escreva a copy de 3 mensagens em sequência: a primeira entregando a isca digital prometida, a segunda (enviada 2 min depois) verificando se a pessoa conseguiu acessar e quebrando objeções, e a terceira conectando a isca a uma oferta do meu produto de ticket baixo.",
    username: "automacao.pro",
    avatar: "AP",
    postTitle: "MANYCHAT INTELIGENTE",
    postSubtitle: "Leads Frios em Clientes Ativos",
    gradient: "from-violet-950 via-neutral-900 to-black",
  },
  {
    id: 6,
    title: "Banco de Títulos Magnéticos (Hooks de Capa)",
    desc: "Vinte Modelos de copys testadas para capas e reels prontos para preencher e viralizar no feed.",
    category: "Roteiros",
    text: "Liste 20 fórmulas de títulos magnéticos (hooks) para capas de vídeos curtos. Os modelos devem incitar extrema curiosidade, instigar medo de perder algo (FOMO) ou apresentar um contrassenso (ex: 'Porque fazer [X] está destruindo seu [Y]'). Forneça 3 exemplos práticos para cada fórmula aplicados ao meu nicho.",
    username: "copymaster",
    avatar: "CM",
    postTitle: "20 HOOKS DE CAPA",
    postSubtitle: "Títulos e Copys Prontas para Viralizar",
    gradient: "from-rose-950 via-neutral-900 to-black",
  },
  {
    id: 7,
    title: "Cronograma de Postagens 30 Dias do Zero",
    desc: "Planeje e escreva um mês de conteúdos estratégicos de valor e engajamento em poucos minutos.",
    category: "Feed",
    text: "Com base nos pilares de conteúdo já definidos, elabore um cronograma de postagens de 30 dias distribuídos num calendário visual (tabela). Para cada dia, indique: Tema, Formato (Carrossel, Reels, Stories, etc.), Objetivo (Engajar, Atrair, Vender) e o Gatilho mental a ser acionado.",
    username: "jornada_digital",
    avatar: "JD",
    postTitle: "30 DIAS DO ZERO",
    postSubtitle: "Cronograma de Conteúdo Estratégico",
    gradient: "from-emerald-950 via-neutral-900 to-black",
  },
  {
    id: 8,
    title: "Funil de Direct Lucrativo e Conversor",
    desc: "Prompts para treinar o Claude a qualificar e interagir com leads quentes sem parecer robótico.",
    category: "Vendas",
    text: "Eu uso o Direct do Instagram para fechar vendas ativas (High Ticket). Crie um script de qualificação de 4 perguntas abertas que eu devo fazer ao lead interessado para diagnosticar o momento, identificar se ele tem poder aquisitivo e apresentar uma call agendada sem parecer desesperado por vender.",
    username: "conversao_max",
    avatar: "CM",
    postTitle: "FUNIL DE DIRECT",
    postSubtitle: "Claude Qualificando Seus Leads Frios",
    gradient: "from-blue-950 via-slate-900 to-black",
  },
  {
    id: 9,
    title: "Analisador Visual de Feedback & Comentários",
    desc: "Gere respostas inteligentes baseadas no tom de voz ideal do seu perfil automaticamente.",
    category: "Vendas",
    text: "Analise os comentários que recebi na minha última campanha (colar aqui). Agrupe as objeções em categorias principais. Baseado nessas objeções, redija FAQs e crie sugestões de novos conteúdos que quebrem essas dúvidas antes mesmo delas surgirem para a próxima audiência.",
    username: "branding_insights",
    avatar: "BI",
    postTitle: "ANALISADOR COMUNIDADE",
    postSubtitle: "Tom de Voz Perfeito e Automático",
    gradient: "from-sky-950 via-neutral-900 to-black",
  },
  {
    id: 10,
    title: "Roteiro de Carrossel de Alta Retenção",
    desc: "A sequência de dobras de slides visualmente envolventes projetada para audiências exigentes.",
    category: "Feed",
    text: "Monte a estrutura textual de um carrossel de 8 slides. Slide 1: Título polêmico e Subtítulo. Slide 2: Explicação da dor amplificada. Slides 3 a 6: O método em passos rápidos focando no que e não apenas como. Slide 7: Resumo prático (Checklist). Slide 8: CTA claro pedindo salvamento. Utilize espaçamentos amplos e gatilhos de curiosidade na passagem de cada slide.",
    username: "design_magnetico",
    avatar: "DM",
    postTitle: "CARROSSEL RETENÇÃO",
    postSubtitle: "Sequência Ideal de Dobras e CTA",
    gradient: "from-amber-950 via-neutral-900 to-black",
  },
  {
    id: 11,
    title: "Otimizador de Bio de Instagram Milionária",
    desc: "Descubra e escreva uma oferta de promessa direta irresistível que força cliques no seu link da Bio.",
    category: "Diagnóstico",
    text: "Me dê 5 sugestões de reformulação da minha Bio no Instagram (Cole sua bio atual: [inserir]). A bio deve ter: Uma transformação clara de 1ª linha. Em quem eu ajudo na 2ª. Diferencial competitivo ou prova de autoridade na 3ª. E uma chamada para ação (CTA) criativa na última, conectada a um link de oferta.",
    username: "perfil_lucrativo",
    avatar: "PL",
    postTitle: "BIO MILIONÁRIA",
    postSubtitle: "Sua Promessa Direta Irresistível",
    gradient: "from-orange-950 via-neutral-900 to-black",
  },
  {
    id: 12,
    title: "Abordagem Comercial de Parcerias e Altas Colabs",
    desc: "Estrutura rápida para abordar marcas e perfis maiores garantindo abertura e bons acordos.",
    category: "Vendas",
    text: "Escreva 3 modelos de email/direct ('Cold message') para abordar influenciadores maiores no meu nicho. O tom não deve ser o de fã, e sim de uma parceria em que ambas as partes ganham monetariamente. O texto deve ser curto, persuasivo e focado no benefício financeiro direto e no modelo de divisão de receitas.",
    username: "colab_expert",
    avatar: "CE",
    postTitle: "ABORDAGEM EM ESCALA",
    postSubtitle: "Feche Grandes Colaborações de Sucesso",
    gradient: "from-teal-950 via-neutral-900 to-black",
  }
];

export const CATEGORIES = ["Todos", "Diagnóstico", "Roteiros", "Feed", "Stories", "Vendas"];
